server {
    listen 80;
    server_name _;

    # Root directory where your static files were copied
    root /var/www/html/softy-pinko-front-end;

    # Default file to load
    index index.html;

    # Allow serving all files inside this directory
    location / {
        try_files $uri $uri/ =404;
    }
}
