version: "3.8"

services:
  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task4
    ports:
      - "5252:5252"

  front-end:
    build:
      context: .
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    ports:
      - "8080:80"
    depends_on:
      - back-end

